version: '2'
services:
    tasks_mongodb-app:
        image: tasks_mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://tasks_mongodb-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=tasks_mongodb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tasks_mongodb-mongodb:
        extends:
            file: mongodb.yml
            service: tasks_mongodb-mongodb
